"""Add unique constraint to attendance

Revision ID: e277f834c838
Revises: 8514c8a10cb6
Create Date: 2026-07-04 15:45:04.023543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e277f834c838'
down_revision: Union[str, None] = '8514c8a10cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_attendances_member_session', 'attendances', ['member_id', 'session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attendances_member_session', 'attendances', type_='unique')
    # ### end Alembic commands ###
