"""add_persistent_evidence_fields_to_attendances

Revision ID: d3e251b070eb
Revises: ba5a92f8205f
Create Date: 2026-07-05 22:06:08.236144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# No custom imports

# revision identifiers, used by Alembic.
revision: str = 'd3e251b070eb'
down_revision: Union[str, None] = 'ba5a92f8205f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('selfie_image_path', sa.String(length=1024), nullable=True))
    op.add_column('attendances', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('attendances', sa.Column('gps_longitude', sa.Float(), nullable=True))
    op.add_column('attendances', sa.Column('gps_accuracy', sa.Float(), nullable=True))
    op.add_column('attendances', sa.Column('device_name', sa.String(length=255), nullable=True))
    op.add_column('attendances', sa.Column('browser_name', sa.String(length=255), nullable=True))
    op.add_column('attendances', sa.Column('user_agent', sa.String(length=512), nullable=True))
    op.add_column('attendances', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('attendances', sa.Column('captured_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'captured_at')
    op.drop_column('attendances', 'ip_address')
    op.drop_column('attendances', 'user_agent')
    op.drop_column('attendances', 'browser_name')
    op.drop_column('attendances', 'device_name')
    op.drop_column('attendances', 'gps_accuracy')
    op.drop_column('attendances', 'gps_longitude')
    op.drop_column('attendances', 'gps_latitude')
    op.drop_column('attendances', 'selfie_image_path')
    # ### end Alembic commands ###
