from datetime import datetime, timedelta, timezone
from typing import Any, Union
import warnings
from jose import jwt

# Patch passlib/bcrypt compatibility issue before importing passlib
try:
    import bcrypt
    if not hasattr(bcrypt, "__about__"):
        class DummyAbout:
            __version__ = getattr(bcrypt, "__version__", "4.0.0")
        bcrypt.__about__ = DummyAbout()
        
    _original_hashpw = bcrypt.hashpw
    def patched_hashpw(password, salt):
        if isinstance(password, bytes):
            if len(password) > 72:
                password = password[:72]
        elif isinstance(password, str):
            encoded = password.encode('utf-8')
            if len(encoded) > 72:
                password = encoded[:72]
        return _original_hashpw(password, salt)
    bcrypt.hashpw = patched_hashpw

    _original_checkpw = bcrypt.checkpw
    def patched_checkpw(password, hashed_password):
        if isinstance(password, bytes):
            if len(password) > 72:
                password = password[:72]
        elif isinstance(password, str):
            encoded = password.encode('utf-8')
            if len(encoded) > 72:
                password = encoded[:72]
        return _original_checkpw(password, hashed_password)
    bcrypt.checkpw = patched_checkpw
except ImportError:
    pass


# Filter warnings generated by unmaintained passlib library interacting with newer bcrypt
warnings.filterwarnings("ignore", category=UserWarning, module="passlib")
warnings.filterwarnings("ignore", category=DeprecationWarning, module="passlib")
from passlib.context import CryptContext
from app.core.config import settings



# Hashing context using bcrypt algorithm
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify a plain text password against a bcrypt hash."""
    return pwd_context.verify(plain_password, hashed_password)

def get_password_hash(password: str) -> str:
    """Generate a bcrypt hash of a plain text password."""
    return pwd_context.hash(password)

def create_access_token(
    subject: Union[str, Any], 
    role: str,
    expires_delta: Union[timedelta, None] = None
) -> str:
    """
    Generate a JSON Web Token (JWT) for authenticated sessions.
    
    Args:
        subject: Unique identifier (usually user id or email) for the token owner.
        role: User privilege role (SystemAdmin, OrgAdmin, Coordinator, Member, Auditor).
        expires_delta: Custom token duration. Defaults to settings.ACCESS_TOKEN_EXPIRE_MINUTES.
    """
    if expires_delta:
        expire = datetime.now(timezone.utc) + expires_delta
    else:
        expire = datetime.now(timezone.utc) + timedelta(
            minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES
        )
    
    to_encode = {
        "exp": expire, 
        "sub": str(subject),
        "role": role
    }
    
    encoded_jwt = jwt.encode(
        to_encode, 
        settings.SECRET_KEY, 
        algorithm=settings.ALGORITHM
    )
    return encoded_jwt

def decode_access_token(token: str) -> Union[dict, None]:
    """
    Decode and validate a JWT access token.
    
    Returns:
        Dictionary payload if valid, otherwise None.
    """
    try:
        payload = jwt.decode(
            token, 
            settings.SECRET_KEY, 
            algorithms=[settings.ALGORITHM]
        )
        return payload
    except jwt.JWTError:
        return None
